# Recovery and Continuation System Configuration
# Autonomous design for comprehensive recovery capabilities

recovery_settings:
  # Checkpoint intervals
  checkpoint_frequency:
    auto_save_seconds: 300  # Every 5 minutes
    major_milestone_save: true
    phase_completion_save: true
    error_occurrence_save: true
    
  # State persistence locations
  persistence:
    state_file: "recovery/system_state.json"
    progress_file: "recovery/progress_tracker.json"
    agent_states_file: "recovery/agent_states.json"
    llm_optimization_file: "recovery/llm_optimization_state.json"
    data_integrity_file: "recovery/data_integrity.json"
    
  # Recovery validation
  validation:
    state_integrity_check: true
    data_consistency_check: true
    agent_health_verification: true
    llm_model_availability: true
    api_connectivity_test: true
    
  # Continuation strategy
  continuation:
    auto_detect_previous_session: true
    resume_from_last_checkpoint: true
    validate_before_continue: true
    repair_corrupted_state: true
    rollback_on_critical_error: true

# Agent System Recovery
agent_recovery:
  health_monitoring:
    heartbeat_interval: 60  # seconds
    failure_detection_timeout: 180
    max_retry_attempts: 3
    exponential_backoff: true
    
  restart_strategies:
    individual_agent_restart: true
    full_system_restart: false  # Only as last resort
    preserve_completed_work: true
    maintain_cross_agent_state: true
    
  load_balancing:
    redistribute_failed_tasks: true
    priority_preservation: true
    discipline_affinity: true  # Keep agents working on same disciplines

# LLM Optimization Recovery
llm_recovery:
  model_availability:
    check_model_status: true
    fallback_model_selection: true
    cost_optimization_persistence: true
    performance_history_tracking: true
    
  token_usage_tracking:
    persistent_usage_counters: true
    cost_accumulation_tracking: true
    optimization_history: true
    model_performance_metrics: true

# Data Recovery and Integrity
data_recovery:
  standards_data:
    incremental_backup: true
    version_control_integration: true
    corruption_detection: true
    auto_repair_capabilities: true
    
  discipline_organization:
    maintain_directory_structure: true
    preserve_cross_references: true
    validate_data_completeness: true
    repair_missing_connections: true

# Error Handling and Logging
error_handling:
  logging:
    detailed_error_logging: true
    recovery_action_logging: true
    performance_impact_tracking: true
    user_notification_system: true
    
  escalation:
    automatic_error_resolution: true
    escalation_thresholds:
      minor_errors: 5
      major_errors: 2
      critical_errors: 1
    notification_levels:
      - "auto_resolve"
      - "log_and_continue"
      - "pause_and_alert"
      - "full_system_stop"

# Streamlit Interface Recovery
interface_recovery:
  session_state:
    preserve_user_selections: true
    maintain_dashboard_state: true
    restore_progress_displays: true
    recover_filter_settings: true
    
  real_time_updates:
    reconnect_progress_streams: true
    restore_agent_monitoring: true
    reinitialize_llm_dashboard: true
    validate_data_connections: true

# Performance Monitoring for Recovery
performance_monitoring:
  system_metrics:
    memory_usage_tracking: true
    cpu_utilization_monitoring: true
    disk_space_monitoring: true
    network_connectivity_status: true
    
  recovery_metrics:
    recovery_time_tracking: true
    data_loss_assessment: true
    continuation_success_rate: true
    system_stability_metrics: true

# Autonomous Decision Framework
autonomous_decisions:
  decision_logging:
    log_all_autonomous_choices: true
    document_reasoning_process: true
    track_assumption_validity: true
    maintain_decision_audit_trail: true
    
  decision_categories:
    - "llm_model_selection"
    - "error_resolution_strategy"
    - "data_source_prioritization"
    - "agent_task_distribution"
    - "quality_threshold_adjustments"
    
  validation_framework:
    post_decision_validation: true
    assumption_verification: true
    outcome_assessment: true
    learning_from_decisions: true