# Educational Standards Ecosystem Mapping
# Autonomous mapping of major educational standards organizations
# All data will be dynamically discovered at runtime - this provides search framework

# Major International Standards Organizations (URLs will be dynamically discovered)
international_organizations:
  accreditation_bodies:
    - name: "ABET"
      focus: ["Engineering", "Computer_Science", "Applied_Science"]
      search_terms: ["ABET accreditation", "engineering program standards", "computing accreditation"]
      
    - name: "LCME"
      focus: ["Health_Sciences", "Medicine"]
      search_terms: ["LCME standards", "medical education accreditation", "MD program requirements"]
      
    - name: "AACSB"
      focus: ["Business", "Management"]
      search_terms: ["AACSB accreditation", "business school standards", "MBA requirements"]
      
    - name: "ACS"
      focus: ["Physical_Sciences", "Chemistry"]
      search_terms: ["ACS program approval", "chemistry curriculum standards", "undergraduate chemistry"]

  curriculum_standards:
    - name: "Next Generation Science Standards"
      focus: ["Physical_Sciences", "Life_Sciences", "Earth_Sciences"]
      search_terms: ["NGSS", "science education standards", "K-12 science curriculum"]
      
    - name: "Common Core State Standards"
      focus: ["Mathematics", "Literature"]
      search_terms: ["Common Core", "mathematics standards", "English language arts standards"]
      
    - name: "College Board Standards"
      focus: ["All_Disciplines"]
      search_terms: ["AP curriculum", "college board standards", "advanced placement requirements"]

  assessment_standards:
    - name: "MCAT"
      focus: ["Physical_Sciences", "Life_Sciences", "Health_Sciences"]
      search_terms: ["MCAT content", "medical college admission test", "pre-med requirements"]
      
    - name: "GRE Subject Tests"
      focus: ["Physical_Sciences", "Life_Sciences", "Mathematics", "Computer_Science", "Psychology"]
      search_terms: ["GRE subject test", "graduate record examination", "subject test content"]

# Regional/National Standards Bodies (discovered dynamically by region)
regional_standards:
  north_america:
    - "Department of Education standards"
    - "State education departments"
    - "Provincial education ministries"
    
  europe:
    - "European Qualifications Framework"
    - "Bologna Process standards"
    - "National education agencies"
    
  asia_pacific:
    - "ASEAN education standards"
    - "National qualification frameworks"
    - "Regional accreditation bodies"

# Professional Society Standards (per discipline)
professional_societies:
  Physical_Sciences:
    - "American Physical Society"
    - "Institute of Physics"
    - "American Chemical Society"
    - "Royal Society of Chemistry"
    
  Engineering:
    - "IEEE"
    - "ASME"
    - "ASCE"
    - "AIChE"
    
  Health_Sciences:
    - "American Medical Association"
    - "World Health Organization"
    - "National Institutes of Health"
    
  Computer_Science:
    - "ACM"
    - "IEEE Computer Society"
    - "Computing Research Association"

# Search Strategy Framework (for dynamic discovery)
discovery_strategies:
  web_search_patterns:
    - "{discipline} education standards"
    - "{discipline} curriculum guidelines"
    - "{discipline} accreditation requirements"
    - "international {discipline} standards"
    - "{level} {discipline} learning outcomes"
    
  api_endpoints:
    - "Education ministry APIs"
    - "Standards organization databases"  
    - "Academic database APIs"
    - "Professional society resources"
    
  document_types:
    - "Curriculum guidelines"
    - "Learning objectives"
    - "Assessment frameworks"
    - "Accreditation standards"
    - "Professional competencies"

# Dynamic Discovery Indicators (what to look for)
standards_indicators:
  document_patterns:
    - "learning objectives"
    - "curriculum standards"
    - "educational outcomes"
    - "competency framework"
    - "assessment criteria"
    - "accreditation requirements"
    
  authority_indicators:
    - "official government"
    - "ministry of education"
    - "department of education"
    - "accreditation body"
    - "professional association"
    - "international organization"

# Quality Validation Framework
quality_criteria:
  authority_validation:
    - "Government endorsement"
    - "Professional recognition"
    - "International acceptance"
    - "Academic adoption"
    
  content_validation:
    - "Comprehensive coverage"
    - "Recent updates"
    - "Clear learning outcomes"
    - "Assessment alignment"
    
  implementation_validation:
    - "Institutional adoption"
    - "Student outcomes"
    - "Employer recognition"
    - "Transferability"